# Generated by Django 3.0.5 on 2020-04-03 12:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.User.user_directory_path, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wxchat',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信号'),
        ),
    ]
