# Generated by Django 3.0.5 on 2020-04-05 02:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200403_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='0/avator/default.png', upload_to=user.models.User.user_directory_path, verbose_name='用户头像'),
        ),
    ]
