# Generated by Django 3.0.5 on 2020-04-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0006_auto_20200426_1104'),
        ('hotel', '0003_hotelcomment_score'),
        ('user', '0006_auto_20200405_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLovedScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '收藏'), (2, '去过')], verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('loved_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Scene', verbose_name='收藏景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'mt_user_scene',
            },
        ),
        migrations.CreateModel(
            name='UserLovedHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '收藏'), (2, '去过')], verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('loved_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='收藏酒店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'mt_user_hotel',
            },
        ),
    ]
