# Generated by Django 3.0.5 on 2020-04-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userlovedhotel_userlovedscene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlovedhotel',
            old_name='loved_hotel',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='userlovedscene',
            old_name='loved_scene',
            new_name='scene',
        ),
    ]
