# Generated by Django 3.0.5 on 2020-04-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scene', '0003_auto_20200423_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='酒店名称')),
                ('country', models.CharField(default='中国', max_length=255, verbose_name='所在国家')),
                ('address', models.CharField(blank=True, max_length=1024, verbose_name='地址')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='hotel', verbose_name='主展示图片')),
                ('score', models.CharField(default='暂无评分', max_length=10, verbose_name='评分')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('type', models.IntegerField(choices=[(1, '无'), (2, '一星级'), (3, '二星级'), (4, '三星级'), (5, '四星级'), (6, '五星级')], default=1, verbose_name='星级')),
                ('summary', models.TextField(blank=True, verbose_name='景点介绍')),
                ('phone', models.CharField(blank=True, max_length=1024, verbose_name='联系电话')),
                ('price', models.CharField(blank=True, max_length=1024, verbose_name='价格')),
                ('traffic', models.CharField(blank=True, max_length=1024, verbose_name='交通')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'db_table': 'mt_hotel',
            },
        ),
    ]
