# Generated by Django 3.0.5 on 2020-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ename',
            field=models.CharField(blank=True, max_length=255, verbose_name='英文名称'),
        ),
    ]
