# Generated by Django 3.0.5 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcomment',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='评分'),
            preserve_default=False,
        ),
    ]
