# Generated by Django 3.0.5 on 2020-05-09 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_hotelcomment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '标准间'), (2, '单人间'), (3, '双人间'), (4, '三人间'), (5, '大床房'), (6, '亲子间')], verbose_name='房型')),
                ('main_photo', models.ImageField(default='0/avator/default.png', upload_to=hotel.models.HotelRoomType.hotel_room_photo_path, verbose_name='房型照片')),
                ('price', models.IntegerField(verbose_name='房价')),
                ('area', models.IntegerField(verbose_name='面积')),
                ('has_tv', models.IntegerField(choices=[(0, '无'), (1, '有')], verbose_name='电视')),
                ('has_phone', models.IntegerField(choices=[(0, '无'), (1, '有')], verbose_name='电话')),
                ('has_toilet', models.IntegerField(choices=[(0, '无'), (1, '有')], verbose_name='独立卫生间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '各酒店房间类型',
                'verbose_name_plural': '各酒店房间类型',
                'db_table': 'mt_hotel_room_type',
                'unique_together': {('hotel', 'type')},
            },
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('people_number', models.IntegerField(default=1, verbose_name='入住人数')),
                ('in_date', models.DateField(verbose_name='入住时间')),
                ('out_date', models.DateField(verbose_name='离开时间')),
                ('check_room_num', models.IntegerField(default=1, verbose_name='预订数量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='酒店')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelRoomType', verbose_name='房间类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店预订',
                'verbose_name_plural': '酒店预订',
                'db_table': 'mt_hotel_reservation',
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='房间号码')),
                ('status', models.IntegerField(choices=[(0, '空闲'), (1, '入住中'), (2, '已预订'), (3, '不可用')], default=0, verbose_name='房间状态')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='酒店')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelRoomType', verbose_name='房型')),
            ],
            options={
                'verbose_name': '酒店房间',
                'verbose_name_plural': '酒店房间',
                'db_table': 'mt_hotel_room',
                'unique_together': {('hotel', 'number')},
            },
        ),
    ]
