# Generated by Django 3.0.5 on 2020-04-28 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_hotelcomment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=32, verbose_name='房型')),
                ('room_price', models.IntegerField(verbose_name='房价')),
                ('room_count', models.IntegerField(default=0, verbose_name='房间数')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '酒店房间',
                'verbose_name_plural': '酒店房间',
                'db_table': 'mt_hotel_room',
            },
        ),
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='酒店')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.HotelRoom', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '酒店订单',
                'verbose_name_plural': '酒店订单',
                'db_table': 'mt_hotel_order',
            },
        ),
    ]
