# Generated by Django 3.0.5 on 2020-04-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_index', models.IntegerField(verbose_name='省属市索引')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '地级市',
                'verbose_name_plural': '地级市',
                'db_table': 'mt_city',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'mt_province',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='景点名称')),
                ('ename', models.CharField(blank=True, max_length=255, verbose_name='英文名称')),
                ('address', models.CharField(blank=True, max_length=1024, verbose_name='地址')),
                ('hot', models.IntegerField(default=0, verbose_name='热度（点击量）')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='scene', verbose_name='主展示图片')),
                ('score', models.CharField(default='暂无评分', max_length=10, verbose_name='评分')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('travelbook_num', models.IntegerField(default=0, verbose_name='攻略数')),
                ('type', models.IntegerField(choices=[(1, '其他'), (2, '自然'), (3, '文化'), (4, '历史'), (5, '建筑'), (6, '公园')], default=1, verbose_name='分类')),
                ('summary', models.TextField(blank=True, verbose_name='景点介绍')),
                ('phone', models.CharField(blank=True, max_length=1024, verbose_name='联系电话')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='网址')),
                ('open_time', models.CharField(blank=True, max_length=1024, verbose_name='开放时间')),
                ('ticket', models.CharField(blank=True, max_length=1024, verbose_name='门票')),
                ('traffic', models.CharField(blank=True, max_length=1024, verbose_name='交通')),
                ('grade', models.IntegerField(choices=[(1, '无'), (2, 'A级'), (3, 'AA级'), (4, 'AAA级'), (5, 'AAAA级'), (6, 'AAAAA级')], default=1, verbose_name='景区等级')),
                ('advice_time', models.CharField(blank=True, max_length=1024, verbose_name='建议时间')),
                ('tips', models.TextField(blank=True, verbose_name='小提示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.City', verbose_name='所在城市')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Province', verbose_name='所在省')),
            ],
            options={
                'verbose_name': '景区',
                'verbose_name_plural': '景区',
                'db_table': 'mt_scene',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Province', verbose_name='所在省'),
        ),
    ]
