# Generated by Django 3.0.5 on 2020-04-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='country',
            field=models.CharField(default='中国', max_length=255, verbose_name='所在国家'),
        ),
    ]
