# Generated by Django 3.0.5 on 2020-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_scene_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hot',
            field=models.IntegerField(default=1000, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='city',
            name='summary',
            field=models.CharField(default='', max_length=1024, verbose_name='景点概括'),
        ),
    ]
