# Generated by Django 3.0.5 on 2020-04-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scene', '0003_auto_20200423_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Scene', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '景点评论',
                'verbose_name_plural': '景点评论',
                'db_table': 'mt_scene_comment',
            },
        ),
    ]
