# Generated by Django 3.0.5 on 2020-04-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_scenecomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenecomment',
            name='content',
            field=models.CharField(max_length=10240, verbose_name='评论内容'),
        ),
    ]
