# Generated by Django 3.0.5 on 2020-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0006_auto_20200426_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='type',
            field=models.IntegerField(choices=[(1, '其他'), (2, '自然'), (3, '文化'), (4, '历史'), (5, '建筑'), (6, '公园'), (7, '休闲')], default=1, verbose_name='分类'),
        ),
    ]
