# Generated by Django 3.0.5 on 2020-05-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0007_auto_20200429_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
