# Generated by Django 3.0.5 on 2020-05-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0008_auto_20200507_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='hot',
            field=models.PositiveIntegerField(default=1000, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='hot',
            field=models.PositiveIntegerField(default=0, verbose_name='热度（点击量）'),
        ),
    ]
